<a href="https://colab.research.google.com/github/Madhuriganji/AI_ML_Avanthi_Madhuri/blob/main/1_2_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
b.shape

(2, 3)

In [7]:
a=np.array([1,2,3],dtype='int64')
a.itemsize

8

In [8]:
a=np.array([1,2,3,4,5,6,7],[8,9,10,11,12,13,14])
print(a)

([1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14])


In [20]:
b=np.array([1,2],[3,4],[5,6],[7,8])
print(: ,1, :)

SyntaxError: invalid syntax (<ipython-input-20-d47b50567934>, line 2)

In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#All 0s matrix
np.zeros(2,3)