<a href="https://colab.research.google.com/github/Madhuriganji/AI_ML_Avanthi_Madhuri/blob/main/1_2_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
a=np.ones([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.min(stats)

1

In [11]:
np.max(stats)

6

In [13]:
np.max(stats,axis=0)

array([4, 5, 6])

In [14]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print (before)


[[1 2 3 4]
 [5 6 7 8]]


In [19]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print (before)

after= before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])